import numpy as np
import matplotlib.pyplot as plt
import os

## @file
#  This script visualizes data from a text file generated by a C program.
#  It uses matplotlib to create a heatmap of the data values.

## Path to the data file.
file_path = "finitedifference.txt"

## Check if the data file exists.
if os.path.exists(file_path):
    print("Loading data from:", file_path)
    
    ## Load data from the file.
    #  Uses numpy's loadtxt to read the data into an array.
    data = np.loadtxt(file_path)

    ## Create a figure and an axis.
    #  @var fig The figure object for the plot.
    #  @var ax The axis object for the plot.
    fig, ax = plt.subplots()
    
    ## Display the data as an image.
    #  @var im The image object created from the data array.
    im = ax.imshow(data, cmap='bwr', origin='lower')
    
    ## Add a colorbar to the plot to show the data scale.
    plt.colorbar(im)
    
    ## Set the title of the plot.
    plt.title("finitedifference.txt")
    
    ## Show the plot on the screen.
    plt.show()
else:
    ## Print an error message if the file is not found.
    print("File finitedifference.txt not found in the current directory.")
